# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DatapipeServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStreamServerEvents = channel.unary_stream(
                '/datapipe.DatapipeService/GetStreamServerEvents',
                request_serializer=agent__pb2.ServerEventsRequest.SerializeToString,
                response_deserializer=agent__pb2.ServerEventsResponse.FromString,
                _registered_method=True)
        self.SendData = channel.unary_unary(
                '/datapipe.DatapipeService/SendData',
                request_serializer=agent__pb2.SendDataRequest.SerializeToString,
                response_deserializer=agent__pb2.SendDataResponse.FromString,
                _registered_method=True)
        self.SendGraph = channel.unary_unary(
                '/datapipe.DatapipeService/SendGraph',
                request_serializer=agent__pb2.SendGraphRequest.SerializeToString,
                response_deserializer=agent__pb2.SendGraphResponse.FromString,
                _registered_method=True)
        self.SendLogs = channel.unary_unary(
                '/datapipe.DatapipeService/SendLogs',
                request_serializer=agent__pb2.SendLogsRequest.SerializeToString,
                response_deserializer=agent__pb2.SendLogsResponse.FromString,
                _registered_method=True)
        self.SendRunStatus = channel.unary_unary(
                '/datapipe.DatapipeService/SendRunStatus',
                request_serializer=agent__pb2.SendRunStatusRequest.SerializeToString,
                response_deserializer=agent__pb2.SendRunStatusResponse.FromString,
                _registered_method=True)
        self.SendPing = channel.unary_unary(
                '/datapipe.DatapipeService/SendPing',
                request_serializer=agent__pb2.PingRequest.SerializeToString,
                response_deserializer=agent__pb2.PingResponse.FromString,
                _registered_method=True)


class DatapipeServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetStreamServerEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendRunStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatapipeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStreamServerEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.GetStreamServerEvents,
                    request_deserializer=agent__pb2.ServerEventsRequest.FromString,
                    response_serializer=agent__pb2.ServerEventsResponse.SerializeToString,
            ),
            'SendData': grpc.unary_unary_rpc_method_handler(
                    servicer.SendData,
                    request_deserializer=agent__pb2.SendDataRequest.FromString,
                    response_serializer=agent__pb2.SendDataResponse.SerializeToString,
            ),
            'SendGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.SendGraph,
                    request_deserializer=agent__pb2.SendGraphRequest.FromString,
                    response_serializer=agent__pb2.SendGraphResponse.SerializeToString,
            ),
            'SendLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.SendLogs,
                    request_deserializer=agent__pb2.SendLogsRequest.FromString,
                    response_serializer=agent__pb2.SendLogsResponse.SerializeToString,
            ),
            'SendRunStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SendRunStatus,
                    request_deserializer=agent__pb2.SendRunStatusRequest.FromString,
                    response_serializer=agent__pb2.SendRunStatusResponse.SerializeToString,
            ),
            'SendPing': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPing,
                    request_deserializer=agent__pb2.PingRequest.FromString,
                    response_serializer=agent__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datapipe.DatapipeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('datapipe.DatapipeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DatapipeService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStreamServerEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/datapipe.DatapipeService/GetStreamServerEvents',
            agent__pb2.ServerEventsRequest.SerializeToString,
            agent__pb2.ServerEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datapipe.DatapipeService/SendData',
            agent__pb2.SendDataRequest.SerializeToString,
            agent__pb2.SendDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datapipe.DatapipeService/SendGraph',
            agent__pb2.SendGraphRequest.SerializeToString,
            agent__pb2.SendGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datapipe.DatapipeService/SendLogs',
            agent__pb2.SendLogsRequest.SerializeToString,
            agent__pb2.SendLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendRunStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datapipe.DatapipeService/SendRunStatus',
            agent__pb2.SendRunStatusRequest.SerializeToString,
            agent__pb2.SendRunStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendPing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datapipe.DatapipeService/SendPing',
            agent__pb2.PingRequest.SerializeToString,
            agent__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
