# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import client_pb2 as client__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in client_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClientServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetData = channel.unary_unary(
                '/datapipe.ClientService/GetData',
                request_serializer=client__pb2.GetDataRequest.SerializeToString,
                response_deserializer=client__pb2.GetDataResponse.FromString,
                _registered_method=True)
        self.GetAgents = channel.unary_unary(
                '/datapipe.ClientService/GetAgents',
                request_serializer=client__pb2.GetAgentsRequest.SerializeToString,
                response_deserializer=client__pb2.GetAgentsResponse.FromString,
                _registered_method=True)
        self.RunPipeline = channel.unary_unary(
                '/datapipe.ClientService/RunPipeline',
                request_serializer=client__pb2.RunPipelineRequest.SerializeToString,
                response_deserializer=client__pb2.RunPipelineResponse.FromString,
                _registered_method=True)
        self.GetRunList = channel.unary_unary(
                '/datapipe.ClientService/GetRunList',
                request_serializer=client__pb2.GetRunListRequest.SerializeToString,
                response_deserializer=client__pb2.GetRunListResponse.FromString,
                _registered_method=True)
        self.GetRunLogs = channel.unary_unary(
                '/datapipe.ClientService/GetRunLogs',
                request_serializer=client__pb2.GetRunLogsRequest.SerializeToString,
                response_deserializer=client__pb2.GetRunLogsResponse.FromString,
                _registered_method=True)
        self.GetRunLogsStream = channel.unary_stream(
                '/datapipe.ClientService/GetRunLogsStream',
                request_serializer=client__pb2.GetRunLogsStreamRequest.SerializeToString,
                response_deserializer=client__pb2.GetRunLogsStreamResponse.FromString,
                _registered_method=True)
        self.GetGraph = channel.unary_unary(
                '/datapipe.ClientService/GetGraph',
                request_serializer=client__pb2.GetGraphRequest.SerializeToString,
                response_deserializer=client__pb2.GetGraphResponse.FromString,
                _registered_method=True)


class ClientServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunPipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunLogsStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetData,
                    request_deserializer=client__pb2.GetDataRequest.FromString,
                    response_serializer=client__pb2.GetDataResponse.SerializeToString,
            ),
            'GetAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgents,
                    request_deserializer=client__pb2.GetAgentsRequest.FromString,
                    response_serializer=client__pb2.GetAgentsResponse.SerializeToString,
            ),
            'RunPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.RunPipeline,
                    request_deserializer=client__pb2.RunPipelineRequest.FromString,
                    response_serializer=client__pb2.RunPipelineResponse.SerializeToString,
            ),
            'GetRunList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunList,
                    request_deserializer=client__pb2.GetRunListRequest.FromString,
                    response_serializer=client__pb2.GetRunListResponse.SerializeToString,
            ),
            'GetRunLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunLogs,
                    request_deserializer=client__pb2.GetRunLogsRequest.FromString,
                    response_serializer=client__pb2.GetRunLogsResponse.SerializeToString,
            ),
            'GetRunLogsStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetRunLogsStream,
                    request_deserializer=client__pb2.GetRunLogsStreamRequest.FromString,
                    response_serializer=client__pb2.GetRunLogsStreamResponse.SerializeToString,
            ),
            'GetGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGraph,
                    request_deserializer=client__pb2.GetGraphRequest.FromString,
                    response_serializer=client__pb2.GetGraphResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datapipe.ClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('datapipe.ClientService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datapipe.ClientService/GetData',
            client__pb2.GetDataRequest.SerializeToString,
            client__pb2.GetDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datapipe.ClientService/GetAgents',
            client__pb2.GetAgentsRequest.SerializeToString,
            client__pb2.GetAgentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datapipe.ClientService/RunPipeline',
            client__pb2.RunPipelineRequest.SerializeToString,
            client__pb2.RunPipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datapipe.ClientService/GetRunList',
            client__pb2.GetRunListRequest.SerializeToString,
            client__pb2.GetRunListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datapipe.ClientService/GetRunLogs',
            client__pb2.GetRunLogsRequest.SerializeToString,
            client__pb2.GetRunLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunLogsStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/datapipe.ClientService/GetRunLogsStream',
            client__pb2.GetRunLogsStreamRequest.SerializeToString,
            client__pb2.GetRunLogsStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datapipe.ClientService/GetGraph',
            client__pb2.GetGraphRequest.SerializeToString,
            client__pb2.GetGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
