# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import router_agent_pb2 as router__agent__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in router_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RouterDatapipeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStreamServerEvents = channel.unary_stream(
                '/datapipe.RouterDatapipeService/GetStreamServerEvents',
                request_serializer=router__agent__pb2.ServerEventsRequest.SerializeToString,
                response_deserializer=router__agent__pb2.ServerEventsResponse.FromString,
                _registered_method=True)
        self.SendData = channel.unary_unary(
                '/datapipe.RouterDatapipeService/SendData',
                request_serializer=router__agent__pb2.SendDataRequest.SerializeToString,
                response_deserializer=router__agent__pb2.SendDataResponse.FromString,
                _registered_method=True)
        self.SendGraph = channel.unary_unary(
                '/datapipe.RouterDatapipeService/SendGraph',
                request_serializer=router__agent__pb2.SendGraphRequest.SerializeToString,
                response_deserializer=router__agent__pb2.SendGraphResponse.FromString,
                _registered_method=True)
        self.SendRunCreationStatus = channel.unary_unary(
                '/datapipe.RouterDatapipeService/SendRunCreationStatus',
                request_serializer=router__agent__pb2.SendRunCreationStatusRequest.SerializeToString,
                response_deserializer=router__agent__pb2.SendRunCreationStatusResponse.FromString,
                _registered_method=True)
        self.SendPing = channel.unary_unary(
                '/datapipe.RouterDatapipeService/SendPing',
                request_serializer=router__agent__pb2.PingRequest.SerializeToString,
                response_deserializer=router__agent__pb2.PingResponse.FromString,
                _registered_method=True)


class RouterDatapipeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStreamServerEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendRunCreationStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouterDatapipeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStreamServerEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.GetStreamServerEvents,
                    request_deserializer=router__agent__pb2.ServerEventsRequest.FromString,
                    response_serializer=router__agent__pb2.ServerEventsResponse.SerializeToString,
            ),
            'SendData': grpc.unary_unary_rpc_method_handler(
                    servicer.SendData,
                    request_deserializer=router__agent__pb2.SendDataRequest.FromString,
                    response_serializer=router__agent__pb2.SendDataResponse.SerializeToString,
            ),
            'SendGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.SendGraph,
                    request_deserializer=router__agent__pb2.SendGraphRequest.FromString,
                    response_serializer=router__agent__pb2.SendGraphResponse.SerializeToString,
            ),
            'SendRunCreationStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SendRunCreationStatus,
                    request_deserializer=router__agent__pb2.SendRunCreationStatusRequest.FromString,
                    response_serializer=router__agent__pb2.SendRunCreationStatusResponse.SerializeToString,
            ),
            'SendPing': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPing,
                    request_deserializer=router__agent__pb2.PingRequest.FromString,
                    response_serializer=router__agent__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datapipe.RouterDatapipeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('datapipe.RouterDatapipeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RouterDatapipeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStreamServerEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/datapipe.RouterDatapipeService/GetStreamServerEvents',
            router__agent__pb2.ServerEventsRequest.SerializeToString,
            router__agent__pb2.ServerEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datapipe.RouterDatapipeService/SendData',
            router__agent__pb2.SendDataRequest.SerializeToString,
            router__agent__pb2.SendDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datapipe.RouterDatapipeService/SendGraph',
            router__agent__pb2.SendGraphRequest.SerializeToString,
            router__agent__pb2.SendGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendRunCreationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datapipe.RouterDatapipeService/SendRunCreationStatus',
            router__agent__pb2.SendRunCreationStatusRequest.SerializeToString,
            router__agent__pb2.SendRunCreationStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendPing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datapipe.RouterDatapipeService/SendPing',
            router__agent__pb2.PingRequest.SerializeToString,
            router__agent__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
