# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import router_client_pb2 as router__client__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in router_client_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RouterClientServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAgents = channel.unary_unary(
                '/datapipe.RouterClientService/GetAgents',
                request_serializer=router__client__pb2.GetAgentsRequest.SerializeToString,
                response_deserializer=router__client__pb2.GetAgentsResponse.FromString,
                _registered_method=True)
        self.GetGraph = channel.unary_unary(
                '/datapipe.RouterClientService/GetGraph',
                request_serializer=router__client__pb2.GetGraphRequest.SerializeToString,
                response_deserializer=router__client__pb2.GetGraphResponse.FromString,
                _registered_method=True)
        self.GetData = channel.unary_unary(
                '/datapipe.RouterClientService/GetData',
                request_serializer=router__client__pb2.GetDataRequest.SerializeToString,
                response_deserializer=router__client__pb2.GetDataResponse.FromString,
                _registered_method=True)
        self.RunPipeline = channel.unary_unary(
                '/datapipe.RouterClientService/RunPipeline',
                request_serializer=router__client__pb2.RunPipelineRequest.SerializeToString,
                response_deserializer=router__client__pb2.RunPipelineResponse.FromString,
                _registered_method=True)
        self.CancelPipeline = channel.unary_unary(
                '/datapipe.RouterClientService/CancelPipeline',
                request_serializer=router__client__pb2.CancelPipelineRequest.SerializeToString,
                response_deserializer=router__client__pb2.CancelPipelineResponse.FromString,
                _registered_method=True)


class RouterClientServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunPipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelPipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouterClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgents,
                    request_deserializer=router__client__pb2.GetAgentsRequest.FromString,
                    response_serializer=router__client__pb2.GetAgentsResponse.SerializeToString,
            ),
            'GetGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGraph,
                    request_deserializer=router__client__pb2.GetGraphRequest.FromString,
                    response_serializer=router__client__pb2.GetGraphResponse.SerializeToString,
            ),
            'GetData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetData,
                    request_deserializer=router__client__pb2.GetDataRequest.FromString,
                    response_serializer=router__client__pb2.GetDataResponse.SerializeToString,
            ),
            'RunPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.RunPipeline,
                    request_deserializer=router__client__pb2.RunPipelineRequest.FromString,
                    response_serializer=router__client__pb2.RunPipelineResponse.SerializeToString,
            ),
            'CancelPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelPipeline,
                    request_deserializer=router__client__pb2.CancelPipelineRequest.FromString,
                    response_serializer=router__client__pb2.CancelPipelineResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datapipe.RouterClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('datapipe.RouterClientService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RouterClientService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datapipe.RouterClientService/GetAgents',
            router__client__pb2.GetAgentsRequest.SerializeToString,
            router__client__pb2.GetAgentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datapipe.RouterClientService/GetGraph',
            router__client__pb2.GetGraphRequest.SerializeToString,
            router__client__pb2.GetGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datapipe.RouterClientService/GetData',
            router__client__pb2.GetDataRequest.SerializeToString,
            router__client__pb2.GetDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datapipe.RouterClientService/RunPipeline',
            router__client__pb2.RunPipelineRequest.SerializeToString,
            router__client__pb2.RunPipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datapipe.RouterClientService/CancelPipeline',
            router__client__pb2.CancelPipelineRequest.SerializeToString,
            router__client__pb2.CancelPipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
