# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import storage_client_pb2 as storage__client__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in storage_client_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StorageClientServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRunLogs = channel.unary_unary(
                '/datapipe.StorageClientService/GetRunLogs',
                request_serializer=storage__client__pb2.GetRunLogsRequest.SerializeToString,
                response_deserializer=storage__client__pb2.GetRunLogsResponse.FromString,
                _registered_method=True)
        self.GetRunStatuses = channel.unary_unary(
                '/datapipe.StorageClientService/GetRunStatuses',
                request_serializer=storage__client__pb2.GetRunStatusesRequest.SerializeToString,
                response_deserializer=storage__client__pb2.GetRunStatusesResponse.FromString,
                _registered_method=True)
        self.GetRunLogsStream = channel.unary_stream(
                '/datapipe.StorageClientService/GetRunLogsStream',
                request_serializer=storage__client__pb2.GetRunLogsStreamResponse.SerializeToString,
                response_deserializer=storage__client__pb2.GetRunLogsStreamResponse.FromString,
                _registered_method=True)
        self.GetRunStatuseStream = channel.unary_stream(
                '/datapipe.StorageClientService/GetRunStatuseStream',
                request_serializer=storage__client__pb2.GetRunStatusesStreamRequest.SerializeToString,
                response_deserializer=storage__client__pb2.GetRunStatusesStreamResponse.FromString,
                _registered_method=True)


class StorageClientServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRunLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunStatuses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunLogsStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunStatuseStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRunLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunLogs,
                    request_deserializer=storage__client__pb2.GetRunLogsRequest.FromString,
                    response_serializer=storage__client__pb2.GetRunLogsResponse.SerializeToString,
            ),
            'GetRunStatuses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunStatuses,
                    request_deserializer=storage__client__pb2.GetRunStatusesRequest.FromString,
                    response_serializer=storage__client__pb2.GetRunStatusesResponse.SerializeToString,
            ),
            'GetRunLogsStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetRunLogsStream,
                    request_deserializer=storage__client__pb2.GetRunLogsStreamResponse.FromString,
                    response_serializer=storage__client__pb2.GetRunLogsStreamResponse.SerializeToString,
            ),
            'GetRunStatuseStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetRunStatuseStream,
                    request_deserializer=storage__client__pb2.GetRunStatusesStreamRequest.FromString,
                    response_serializer=storage__client__pb2.GetRunStatusesStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datapipe.StorageClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('datapipe.StorageClientService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StorageClientService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRunLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datapipe.StorageClientService/GetRunLogs',
            storage__client__pb2.GetRunLogsRequest.SerializeToString,
            storage__client__pb2.GetRunLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunStatuses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datapipe.StorageClientService/GetRunStatuses',
            storage__client__pb2.GetRunStatusesRequest.SerializeToString,
            storage__client__pb2.GetRunStatusesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunLogsStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/datapipe.StorageClientService/GetRunLogsStream',
            storage__client__pb2.GetRunLogsStreamResponse.SerializeToString,
            storage__client__pb2.GetRunLogsStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunStatuseStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/datapipe.StorageClientService/GetRunStatuseStream',
            storage__client__pb2.GetRunStatusesStreamRequest.SerializeToString,
            storage__client__pb2.GetRunStatusesStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
