# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: storage_agent.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'storage_agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import storage_client_pb2 as storage__client__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13storage_agent.proto\x12\x08\x64\x61tapipe\x1a\x14storage_client.proto\"B\n\x0fSendLogsRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\x1f\n\x03log\x18\x02 \x01(\x0b\x32\x12.datapipe.LogEvent\"!\n\x10SendLogsResponse\x12\r\n\x05state\x18\x01 \x01(\t\"M\n\x14SendRunStatusRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12%\n\x06status\x18\x02 \x01(\x0b\x32\x15.datapipe.StatusEvent\"&\n\x15SendRunStatusResponse\x12\r\n\x05state\x18\x01 \x01(\t2\xad\x01\n\x16StorageDatapipeService\x12\x41\n\x08SendLogs\x12\x19.datapipe.SendLogsRequest\x1a\x1a.datapipe.SendLogsResponse\x12P\n\rSendRunStatus\x12\x1e.datapipe.SendRunStatusRequest\x1a\x1f.datapipe.SendRunStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'storage_agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDLOGSREQUEST']._serialized_start=55
  _globals['_SENDLOGSREQUEST']._serialized_end=121
  _globals['_SENDLOGSRESPONSE']._serialized_start=123
  _globals['_SENDLOGSRESPONSE']._serialized_end=156
  _globals['_SENDRUNSTATUSREQUEST']._serialized_start=158
  _globals['_SENDRUNSTATUSREQUEST']._serialized_end=235
  _globals['_SENDRUNSTATUSRESPONSE']._serialized_start=237
  _globals['_SENDRUNSTATUSRESPONSE']._serialized_end=275
  _globals['_STORAGEDATAPIPESERVICE']._serialized_start=278
  _globals['_STORAGEDATAPIPESERVICE']._serialized_end=451
# @@protoc_insertion_point(module_scope)
