# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: storage_client.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'storage_client.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14storage_client.proto\x12\x08\x64\x61tapipe\"<\n\x08LogEvent\x12\x11\n\ttimestamp\x18\x01 \x01(\x02\x12\x10\n\x08sequence\x18\x02 \x01(\x03\x12\x0b\n\x03log\x18\x03 \x01(\t\"0\n\x0bStatusEvent\x12\x11\n\ttimestamp\x18\x01 \x01(\x02\x12\x0e\n\x06status\x18\x02 \x01(\t\"#\n\x11GetRunLogsRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\"6\n\x12GetRunLogsResponse\x12 \n\x04logs\x18\x01 \x03(\x0b\x32\x12.datapipe.LogEvent\"\'\n\x15GetRunStatusesRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\"A\n\x16GetRunStatusesResponse\x12\'\n\x08statuses\x18\x01 \x03(\x0b\x32\x15.datapipe.StatusEvent\")\n\x17GetRunLogsStreamRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\";\n\x18GetRunLogsStreamResponse\x12\x1f\n\x03log\x18\x01 \x01(\x0b\x32\x12.datapipe.LogEvent\"-\n\x1bGetRunStatusesStreamRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\"E\n\x1cGetRunStatusesStreamResponse\x12%\n\x06status\x18\x01 \x01(\x0b\x32\x15.datapipe.StatusEvent2\xfa\x02\n\x14StorageClientService\x12G\n\nGetRunLogs\x12\x1b.datapipe.GetRunLogsRequest\x1a\x1c.datapipe.GetRunLogsResponse\x12S\n\x0eGetRunStatuses\x12\x1f.datapipe.GetRunStatusesRequest\x1a .datapipe.GetRunStatusesResponse\x12\\\n\x10GetRunLogsStream\x12\".datapipe.GetRunLogsStreamResponse\x1a\".datapipe.GetRunLogsStreamResponse0\x01\x12\x66\n\x13GetRunStatuseStream\x12%.datapipe.GetRunStatusesStreamRequest\x1a&.datapipe.GetRunStatusesStreamResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'storage_client_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGEVENT']._serialized_start=34
  _globals['_LOGEVENT']._serialized_end=94
  _globals['_STATUSEVENT']._serialized_start=96
  _globals['_STATUSEVENT']._serialized_end=144
  _globals['_GETRUNLOGSREQUEST']._serialized_start=146
  _globals['_GETRUNLOGSREQUEST']._serialized_end=181
  _globals['_GETRUNLOGSRESPONSE']._serialized_start=183
  _globals['_GETRUNLOGSRESPONSE']._serialized_end=237
  _globals['_GETRUNSTATUSESREQUEST']._serialized_start=239
  _globals['_GETRUNSTATUSESREQUEST']._serialized_end=278
  _globals['_GETRUNSTATUSESRESPONSE']._serialized_start=280
  _globals['_GETRUNSTATUSESRESPONSE']._serialized_end=345
  _globals['_GETRUNLOGSSTREAMREQUEST']._serialized_start=347
  _globals['_GETRUNLOGSSTREAMREQUEST']._serialized_end=388
  _globals['_GETRUNLOGSSTREAMRESPONSE']._serialized_start=390
  _globals['_GETRUNLOGSSTREAMRESPONSE']._serialized_end=449
  _globals['_GETRUNSTATUSESSTREAMREQUEST']._serialized_start=451
  _globals['_GETRUNSTATUSESSTREAMREQUEST']._serialized_end=496
  _globals['_GETRUNSTATUSESSTREAMRESPONSE']._serialized_start=498
  _globals['_GETRUNSTATUSESSTREAMRESPONSE']._serialized_end=567
  _globals['_STORAGECLIENTSERVICE']._serialized_start=570
  _globals['_STORAGECLIENTSERVICE']._serialized_end=948
# @@protoc_insertion_point(module_scope)
