# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import storage_agent_pb2 as storage__agent__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in storage_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StorageDatapipeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendLogs = channel.unary_unary(
                '/datapipe.StorageDatapipeService/SendLogs',
                request_serializer=storage__agent__pb2.SendLogsRequest.SerializeToString,
                response_deserializer=storage__agent__pb2.SendLogsResponse.FromString,
                _registered_method=True)
        self.SendRunStatus = channel.unary_unary(
                '/datapipe.StorageDatapipeService/SendRunStatus',
                request_serializer=storage__agent__pb2.SendRunStatusRequest.SerializeToString,
                response_deserializer=storage__agent__pb2.SendRunStatusResponse.FromString,
                _registered_method=True)


class StorageDatapipeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendRunStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StorageDatapipeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.SendLogs,
                    request_deserializer=storage__agent__pb2.SendLogsRequest.FromString,
                    response_serializer=storage__agent__pb2.SendLogsResponse.SerializeToString,
            ),
            'SendRunStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SendRunStatus,
                    request_deserializer=storage__agent__pb2.SendRunStatusRequest.FromString,
                    response_serializer=storage__agent__pb2.SendRunStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datapipe.StorageDatapipeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('datapipe.StorageDatapipeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StorageDatapipeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datapipe.StorageDatapipeService/SendLogs',
            storage__agent__pb2.SendLogsRequest.SerializeToString,
            storage__agent__pb2.SendLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendRunStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datapipe.StorageDatapipeService/SendRunStatus',
            storage__agent__pb2.SendRunStatusRequest.SerializeToString,
            storage__agent__pb2.SendRunStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
