syntax = "proto3";

package datapipe;

import "router_client.proto";

service RouterDatapipeService {
  rpc GetStreamServerEvents(ServerEventsRequest) returns (stream ServerEventsResponse);
  rpc SendData(SendDataRequest) returns (SendDataResponse);
  rpc SendGraph(SendGraphRequest) returns (SendGraphResponse);
  rpc SendRunCreationStatus(SendRunCreationStatusRequest) returns (SendRunCreationStatusResponse);
  rpc SendPing(PingRequest) returns (PingResponse);
}

message ServerEventsRequest {
    string name = 1;
}

message DataEvent {
  string route_id = 1;
  GetDataRequest request = 2;
}

message RunEvent {
  string route_id = 1;
  string run_id = 2;
  repeated LabelsItem labels = 3;
  repeated ChangeList changelist = 4;
}

message PingEvent {

}

message GraphEvent {
  string route_id = 1;
  string label_key = 2;
  string value = 3;
}

message ServerEventsResponse {
  string request_id = 1;
  oneof event {
    DataEvent data_event = 2;
    RunEvent run_event = 3;
    GraphEvent graph_event = 4;
    PingEvent ping_event = 5;
  }
}

message SendDataRequest{
  string route_id = 1;
  TableData data = 2;
}

message SendDataResponse{
  string status = 1;
}

message PingRequest {
  string name = 1;
}

message PingResponse {
  string status = 1;
  string message = 2;
}

message SendGraphRequest {
  string route_id = 1;
  GraphData data = 2;
}

message SendGraphResponse {
  string status = 1;
}

message SendRunCreationStatusRequest{
  string route_id = 1;
  string state = 2;
  string error = 3;
}

message SendRunCreationStatusResponse{
  string state = 1;
}