@host = https://datapipe-example-api-hzkr3iwwhq-ez.a.run.app/

GET {{host}}/api/v1alpha2/graph

###
POST {{host}}/api/v1alpha1/update-data
Content-Type: application/json

{
    "table_name": "events",
    "upsert": [
        {
            "user_id": 1,
            "event_id": 2,
            "event": {
                "event_type":"click",
                "lang":"ru",
                "offer_id":2
            }
        }
    ],
    "enable_changelist": false
}