from __future__ import annotations

from datapipe.compute import Pipeline
from datapipe.datatable import DataStore
from datapipe.step.batch_generate import BatchGenerate
from datapipe.step.batch_transform import BatchTransform
from datapipe.types import Required
from datapipe_app import DatapipeAPI, RunLogsBackend
from datapipe_app.ops.specs import (
    OpsColumn,
    OpsColumnGroup,
    OpsFilterRule,
    OpsMetricTableSpec,
    OpsRelationSpec,
)
from datapipe_app_ml_ops.ops.ops_specs import (
    DatapipeOpsSpec,
    OpsClassMetricTableSpec,
    OpsDataSpec,
    OpsFrozenDatasetSpec,
    OpsImageAnnotationSpec,
    OpsImageDataSpec,
    OpsImagePredictionViewSpec,
    OpsImageRecordViewSpec,
    OpsModelSpec,
    OpsTrainConfigRegistrySpec,
    OpsTrainingRequestSpec,
    OpsTrainingSpec,
)
from datapipe_label_studio.upload_predictions_pipeline import LabelStudioUploadPredictions
from datapipe_label_studio.upload_tasks_pipeline import LabelStudioUploadTasks
from datapipe_ml.metrics.model_selection import FindBestModel
from datapipe_ml.tasks.classification.freeze import ClassificationFreezeDataset
from datapipe_ml.tasks.classification.inference import Inference_ClassificationModel
from datapipe_ml.tasks.classification.metrics import CountMetrics_Subset_ClassificationModel
from datapipe_ml.tasks.classification.train.tensorflow import (
    TF_ClassificationTrainingConfig,
    Train_Tensorflow_ClassificationModel,
)
from datapipe_ml.training.specs import TrainingResumeConfig, TrainingSyncConfig
from datapipe_ml.training.train_config_id import TrainingConfigPreset

import steps
from config import (
    CLICKHOUSE_RUN_LOGS_URL,
    DATAPIPE_DIR,
    DBCONN,
    LABEL_CONFIG,
    LABEL_STUDIO_API_KEY,
    LABEL_STUDIO_URL,
    PROJECT_NAME,
    datapipe_tmp_folder,
    gpu_executor,
    label_studio_storages,
    metrics_executor,
    parallel_io_executor,
)
from data import catalog

pipeline = Pipeline(
    [
        BatchGenerate(
            steps.list_s3_images,
            outputs=["s3_images"],
            labels=[("stage", "annotation")],
        ),
        LabelStudioUploadTasks(
            input__item="s3_images",
            output__label_studio_project_task="ls_task",
            output__label_studio_project_annotation="ls_annotations",
            output__label_studio_sync_table="ls_sync",
            ls_url=LABEL_STUDIO_URL,
            api_key=LABEL_STUDIO_API_KEY,
            project_identifier=PROJECT_NAME,
            project_label_config_at_create=LABEL_CONFIG,
            primary_keys=["image_name"],
            columns=["image_url"],
            storages=label_studio_storages(),
            chunk_size=100,
            labels=[("stage", "annotation")],
        ),
        BatchTransform(
            func=steps.parse_annotations_from_label_studio,
            inputs=["ls_annotations"],
            outputs=["image__ground_truth"],
            labels=[("stage", "annotation")],
            transform_keys=["image_name"],
        ),
        BatchTransform(
            func=steps.split_df_train_val,
            inputs=["image__ground_truth", "image__subset"],
            outputs=["image__subset"],
            labels=[("stage", "train"), ("stage", "train-prepare")],
            transform_keys=["image_name"],
            kwargs=dict(
                primary_keys=["image_name"],
                val_perc=0.25,
                random_seed=42,
            ),
        ),
        ClassificationFreezeDataset(  # type: ignore[list-item]
            input__image="s3_images",
            input__image__ground_truth="image__ground_truth",
            input__subset__has__image="image__subset",
            output__classification_frozen_dataset="classification_frozen_dataset",
            output__classification_frozen_dataset__has__image_gt="classification_frozen_dataset__has__image_gt",
            working_dir=str(DATAPIPE_DIR),
            min_within_time="15min",
            min_delta=10,
            primary_keys=["image_name"],
            image__image_path__name="image_url",
            labels=[("stage", "train"), ("stage", "train-prepare")],
        ),
        Train_Tensorflow_ClassificationModel(  # type: ignore[list-item]
            input__classification_frozen_dataset="classification_frozen_dataset",
            input__classification_frozen_dataset__has__image_gt="classification_frozen_dataset__has__image_gt",
            output__tf_classification_train_config="tf_classification_train_config",
            output__tf_classification_custom_train_config="tf_classification_custom_train_config",
            output__classification_training_request="classification_training_request",
            output__classification_model="classification_model",
            output__classification_model_is_trained_on_cls_frozen_dataset=(
                "classification_model_is_trained_on_cls_frozen_dataset"
            ),
            output__training_status="classification_training_status",
            max_within_time="1w",
            working_dir=str(DATAPIPE_DIR),
            tmp_folder=datapipe_tmp_folder(),
            tf_classification_train_configs=[
                TrainingConfigPreset(
                    name="Tiny CNN 128",
                    description="Default TF classification preset (Has Animal / No Animals)",
                    config=TF_ClassificationTrainingConfig(
                        image_size=(128, 128),
                        seed=42,
                        batch_size=8,
                        arch="tiny_cnn",
                        init_lr=0.001,
                        reduce_lr_patience=3,
                        reduce_lr_factor=0.5,
                        early_stopping_patience=8,
                        epochs=20,
                        label_smoothing=0.0,
                        augmentations=True,
                        augment_func_file=None,
                        class_weight=True,
                    ),
                )
            ],
            sync_config=TrainingSyncConfig(
                enabled=True,
                interval_s=30,
                retries=3,
                retry_sleep_s=30,
            ),
            resume_config=TrainingResumeConfig(
                continue_train_failed_models=True,
                min_completed_epochs=1,
                checkpoint="last",
                max_attempts=10,
                reset_attempts_after="10m",
                lease_ttl_s=60,
                heartbeat_interval_s=10,
            ),
            primary_keys=["image_name"],
            labels=[("stage", "train"), ("stage", "train-without-freeze"), ("stage", "train-TF-model")],
            model_suffix="_e2e",
            executor_config=gpu_executor(),
        ),
        Inference_ClassificationModel(
            input__image=["s3_images", "image__subset"],
            input__classification_model="classification_model",
            output__classification_prediction="classification_prediction",
            primary_keys=["image_name"],
            labels=[("stage", "train"), ("stage", "train-without-freeze"), ("stage", "inference")],
            image__image_path__name="image_url",
            batch_size_default=8,
            executor_config=gpu_executor(),
        ),
        CountMetrics_Subset_ClassificationModel(
            input__image__ground_truth="image__ground_truth",
            input__subset__has__image="image__subset",
            input__classification_prediction="classification_prediction",
            output__classification_model__metrics__on__image="classification_model__metrics_on_image",
            output__classification_model__metrics_by_cls_on__subset="classification_model__metrics_by_cls_on_subset",
            output__classification_model__metrics_on__subset="classification_model__metrics_on_subset",
            primary_keys=["image_name"],
            labels=[("stage", "train"), ("stage", "train-without-freeze"), ("stage", "count-metrics")],
            executor_config=metrics_executor(),
        ),
        FindBestModel(
            input__model="classification_model",
            input__model__metrics_on__subset="classification_model__metrics_on_subset",
            output__attr__model__is_best="attr__classification_model__is_best",
            output__best_model="best_classification_model",
            subset_id="val",
            is_best__name="classification_model__is_best",
            primary_keys=["classification_model_id"],
            metric__name="calc__weighted_f1_score",
            func="max",
            group_by=None,
            labels=[("stage", "train"), ("stage", "train-without-freeze"), ("stage", "count-metrics")],
        ),
        BatchTransform(
            func=steps.get_images_without_ground_truth,
            inputs=["s3_images", "image__ground_truth"],
            outputs=["sec__image_without_ground_truth"],
            transform_keys=["image_name"],
            kwargs=dict(primary_keys=["image_name"]),
            labels=[("stage", "annotation")],
        ),
        Inference_ClassificationModel(
            input__image=["s3_images", "sec__image_without_ground_truth"],
            input__classification_model=["classification_model", "best_classification_model"],
            output__classification_prediction="ls_classification_prediction",
            primary_keys=["image_name"],
            labels=[("stage", "annotation")],
            image__image_path__name="image_url",
            batch_size_default=8,
            executor_config=gpu_executor(),
        ),
        BatchTransform(
            func=steps.prediction_to_ls_prediction,
            inputs=["ls_classification_prediction"],
            outputs=["images_with_predictions"],
            transform_keys=["image_name", "classification_model_id"],
            labels=[("stage", "annotation")],
            kwargs=dict(
                primary_keys=["image_name"],
                model_keys=["classification_model_id"],
            ),
        ),
        LabelStudioUploadPredictions(
            input__item__has__prediction="images_with_predictions",
            input__label_studio_project_task="ls_task",
            input__best_model="best_classification_model",
            output__label_studio_project_prediction="ls_predictions",
            output__label_studio_current_model_version="ls_current_model_version",
            ls_url=LABEL_STUDIO_URL,
            api_key=LABEL_STUDIO_API_KEY,
            project_identifier=PROJECT_NAME,
            primary_keys=["image_name", "classification_model_id"],
            model_keys=["classification_model_id"],
            labels=[("stage", "annotation")],
        ),
        BatchTransform(
            func=steps.download_images,
            inputs=["s3_images"],
            outputs=["local_images"],
            transform_keys=["image_name"],
            labels=[("stage", "fiftyone")],
            executor_config=parallel_io_executor(),
            kwargs=dict(
                image__image_path__name="image_url",
                image__local_image_path__name="local_path",
            ),
        ),
        BatchTransform(
            func=steps.publish_to_fiftyone,
            inputs=["local_images"],
            outputs=["fiftyone_images"],
            labels=[("stage", "fiftyone")],
            kwargs=dict(
                primary_keys=["image_name"],
                image__image_path__name="local_path",
            ),
        ),
        BatchTransform(
            func=steps.publish_to_fiftyone_ground_truth,
            inputs=["local_images", Required("image__ground_truth"), Required("image__subset")],
            outputs=["fiftyone_annotations"],
            labels=[("stage", "fiftyone")],
            kwargs=dict(
                primary_keys=["image_name"],
                image__image_path__name="local_path",
            ),
        ),
        BatchTransform(
            func=steps.publish_to_fiftyone_predictions_from_best_model,
            inputs=["local_images", "classification_prediction", Required("best_classification_model")],
            transform_keys=["image_name", "classification_model_id"],
            outputs=["fiftyone_predictions_from_best_model"],
            labels=[("stage", "fiftyone")],
            kwargs=dict(
                primary_keys=["image_name"],
                model_keys=["classification_model_id"],
                image__image_path__name="local_path",
            ),
        ),
    ]
)

ds = DataStore(DBCONN)
app = DatapipeAPI(
    ds,
    catalog,
    pipeline,
    run_logs_backend=RunLogsBackend.clickhouse(CLICKHOUSE_RUN_LOGS_URL),
)

app.add_specs([
    DatapipeOpsSpec(
        id="has_animal",
        title="Has Animal Classification",
        description="TF classification pipeline: Has Animal vs No Animals.",
        icon="tag",
        color="green",
        data=OpsDataSpec(
            tables=[
                "s3_images",
                "image__ground_truth",
                "image__subset",
                "classification_frozen_dataset",
                "classification_model",
                "classification_model__metrics_on_subset",
                "classification_model__metrics_by_cls_on_subset",
            ],
            item_table="s3_images",
            label_table="image__ground_truth",
            subset_table="image__subset",
            image_view=OpsImageDataSpec(
                kind="image",
                image_table="s3_images",
                image_primary_key_columns=("image_name",),
                image_url_column="image_url",
                subset_table="image__subset",
                subset_join_columns={"image_name": "image_name"},
                subset_column="subset_id",
                records_show_subset=True,
                ground_truth=OpsImageAnnotationSpec(
                    table="image__ground_truth",
                    primary_key_columns=("image_name",),
                    bboxes_column=None,
                    labels_column="label",
                    join_columns={"image_name": "image_name"},
                    role="gt",
                ),
                records_show_ground_truth=True,
                preview_size=84,
                modal_max_side=1100,
                detail_max_side=1600,
            ),
        ),
        frozen_dataset=OpsFrozenDatasetSpec(
            table="classification_frozen_dataset",
            id_column="classification_frozen_dataset_id",
            created_at_column="classification_frozen_dataset__created_at",
            label_mode="timestamp",
            split_columns={
                "train": "classification_frozen_dataset__train_images_count",
                "val": "classification_frozen_dataset__val_images_count",
                "test": "classification_frozen_dataset__test_images_count",
            },
            models_count_relation_id="model_trained_on_frozen_dataset",
            record_view=OpsImageRecordViewSpec(
                kind="image",
                table="classification_frozen_dataset__has__image_gt",
                scope_column="classification_frozen_dataset_id",
                primary_key_columns=("image_name", "subset_id"),
                image_url_column="image__image_path",
                bboxes_column=None,
                labels_column="label",
                preview_size=84,
                modal_max_side=1100,
                detail_max_side=1600,
            ),
            columns=[
                OpsColumn(
                    "classification_frozen_dataset_id",
                    "classification_frozen_dataset_id",
                    "classification_frozen_dataset_id",
                    kind="link",
                    link_to="frozen_dataset",
                    filterable=True,
                ),
                OpsColumn(
                    "created_at",
                    "Frozen at",
                    "classification_frozen_dataset__created_at",
                    kind="datetime",
                    filterable=True,
                ),
                OpsColumn("split", "Split", "split", kind="split"),
                OpsColumn("models", "Models", "models_count", kind="models_count"),
            ],
            default_sort=[("created_at", "desc")],
            run_labels=[("stage", "train-prepare")],
        ),
        model=OpsModelSpec(
            table="classification_model",
            id_column="classification_model_id",
            artifact_uri_column="classification_model__model_path",
            is_best_table="attr__classification_model__is_best",
            is_best_column="classification_model__is_best",
            prediction_view=OpsImagePredictionViewSpec(
                kind="image",
                table="classification_prediction",
                model_id_column="classification_model_id",
                image_primary_key_columns=("image_name",),
                image_url_table="s3_images",
                image_url_column="image_url",
                image_url_join_columns={"image_name": "image_name"},
                prediction=OpsImageAnnotationSpec(
                    table="classification_prediction",
                    primary_key_columns=("image_name", "classification_model_id", "prediction__top_n"),
                    bboxes_column=None,
                    labels_column="label",
                    scores_column="prediction__classification_score",
                    role="prediction",
                ),
                ground_truth=OpsImageAnnotationSpec(
                    table="image__ground_truth",
                    primary_key_columns=("image_name",),
                    bboxes_column=None,
                    labels_column="label",
                    join_columns={"image_name": "image_name"},
                    role="gt",
                ),
                subset_table="image__subset",
                subset_join_columns={"image_name": "image_name"},
                subset_column="subset_id",
                metrics_on_image=OpsMetricTableSpec(
                    id="prediction_image_metrics",
                    title="Per-image metrics",
                    table="classification_model__metrics_on_image",
                    metric_source="classification_model__metrics_on_image",
                    primary_key_columns=["image_name", "classification_model_id", "subset_id", "label"],
                    entity_links={},
                    primary_columns=[],
                    metric_columns=[
                        OpsColumn("subset_id", "subset_id", "subset_id", kind="chip", filterable=True),
                        OpsColumn("is_error", "is_error", "calc__is_error", kind="chip"),
                    ],
                ),
                preview_size=84,
                modal_max_side=1100,
                detail_max_side=1600,
            ),
        ),
        training=OpsTrainingSpec(
            status_table="classification_training_status",
            artifact_columns={
                "manifest": "training_status__manifest_path",
                "run_dir": "training_status__run_dir",
            },
            columns=[
                OpsColumn(
                    "run_id",
                    "Run ID",
                    "training_status__run_key",
                    kind="link",
                    link_to="training_run",
                    filterable=True,
                ),
                OpsColumn(
                    "classification_model_id",
                    "classification_model_id",
                    "classification_model_id",
                    kind="link",
                    link_to="model",
                    filterable=True,
                ),
                OpsColumn(
                    "classification_frozen_dataset_id",
                    "classification_frozen_dataset_id",
                    "classification_frozen_dataset_id",
                    kind="link",
                    link_to="frozen_dataset",
                    filterable=True,
                ),
                OpsColumn(
                    "started_at",
                    "Started",
                    "training_status__started_at",
                    kind="datetime",
                    filterable=True,
                ),
                OpsColumn("duration", "Duration", "duration_seconds", kind="duration"),
                OpsColumn(
                    "status",
                    "Status",
                    "training_status__status",
                    kind="status",
                    filterable=True,
                ),
            ],
            default_sort=[("started_at", "desc")],
            experiments=OpsTrainConfigRegistrySpec(
                table="tf_classification_custom_train_config",
                default_table="tf_classification_train_config",
                id_column="classification_train_config_id",
                params_column="classification_train_config__params",
                source_column="train_config__source",
                display_name_column="train_config__display_name",
                description_column="train_config__description",
                config_type_column="train_config__config_type",
                hash_column="train_config__config_hash",
                active_column="train_config__is_active",
                created_at_column="train_config__created_at",
                updated_at_column="train_config__updated_at",
                revision_column="train_config__revision",
                config_type="tf_classification",
            ),
            requests=OpsTrainingRequestSpec(
                table="classification_training_request",
                id_column="training_request_id",
                frozen_dataset_id_column="classification_frozen_dataset_id",
                train_config_id_column="classification_train_config_id",
                kind_column="training_request__kind",
                enabled_column="training_request__enabled",
                force_column="training_request__force",
                max_within_time_column="training_request__max_within_time",
                max_within_time="1w",
                config_source_column="training_request__config_source",
                config_name_snapshot_column="training_request__config_name_snapshot",
                config_params_snapshot_column="training_request__config_params_snapshot",
                config_hash_column="training_request__config_hash",
                requested_at_column="training_request__requested_at",
                requested_by_column="training_request__requested_by",
                client_request_id_column="training_request__client_request_id",
                status_table="classification_training_status",
                status_request_id_column="training_request_id",
                run_labels=[
                    ("stage", "train-without-freeze"),
                ],
            ),
        ),
        relations=[
            OpsRelationSpec(
                id="model_trained_on_frozen_dataset",
                table="classification_model_is_trained_on_cls_frozen_dataset",
                from_entity="model",
                from_column="classification_model_id",
                to_entity="frozen_dataset",
                to_column="classification_frozen_dataset_id",
            )
        ],
        metrics=[
            OpsMetricTableSpec(
                id="model_metrics",
                title="Model metrics",
                table="classification_model__metrics_on_subset",
                metric_source="classification_model__metrics_on_subset",
                primary_key_columns=["classification_model_id", "subset_id"],
                entity_links={
                    "model": "classification_model_id",
                    "subset": "subset_id",
                },
                primary_columns=[
                    OpsColumn(
                        "classification_model_id",
                        "classification_model_id",
                        "classification_model_id",
                        filterable=True,
                        link_to="model",
                    ),
                    OpsColumn("subset_id", "subset_id", "subset_id", kind="chip", filterable=True),
                ],
                metric_columns=[
                    OpsColumnGroup(
                        "Precision",
                        [
                            OpsColumn("weighted_precision", "W-Precision", "calc__weighted_precision", kind="number"),
                            OpsColumn("macro_precision", "M-Precision", "calc__macro_precision", kind="number"),
                        ],
                    ),
                    OpsColumnGroup(
                        "Recall",
                        [
                            OpsColumn("weighted_recall", "W-Recall", "calc__weighted_recall", kind="number"),
                            OpsColumn("macro_recall", "M-Recall", "calc__macro_recall", kind="number"),
                        ],
                    ),
                    OpsColumnGroup(
                        "F1",
                        [
                            OpsColumn("weighted_f1", "W-F1", "calc__weighted_f1_score", kind="number"),
                            OpsColumn("macro_f1", "M-F1", "calc__macro_f1_score", kind="number"),
                        ],
                    ),
                    OpsColumn("accuracy", "Accuracy", "calc__accuracy", kind="number"),
                    OpsColumn("support", "Support", "calc__support", kind="number"),
                ],
                best_metric_column="calc__weighted_f1_score",
                default_sort=[("weighted_f1", "desc")],
                filters=[OpsColumn("subset_filter", "subset_id", "subset_id", kind="chip", filterable=True)],
                default_filters=[OpsFilterRule(column_id="subset_id", operator="equal", value="val")],
            )
        ],
        class_metrics=[
            OpsClassMetricTableSpec(
                id="subset_class_metrics",
                title="Subset class metrics",
                table="classification_model__metrics_by_cls_on_subset",
                metric_source="classification_model__metrics_by_cls_on_subset",
                primary_key_columns=["classification_model_id", "subset_id", "label"],
                entity_links={
                    "model": "classification_model_id",
                    "subset": "subset_id",
                    "class": "label",
                },
                primary_columns=[
                    OpsColumn(
                        "classification_model_id",
                        "classification_model_id",
                        "classification_model_id",
                        filterable=True,
                        link_to="model",
                    ),
                    OpsColumn("subset_id", "subset_id", "subset_id", kind="chip", filterable=True),
                    OpsColumn("label", "Class", "label", filterable=True),
                ],
                metric_columns=[
                    OpsColumn("precision", "Precision", "calc__precision", kind="number"),
                    OpsColumn("recall", "Recall", "calc__recall", kind="number"),
                    OpsColumn("f1", "F1", "calc__f1_score", kind="number"),
                    OpsColumn("support", "Support", "calc__support", kind="number"),
                    OpsColumn("tp", "TP", "calc__TP", kind="number"),
                    OpsColumn("fp", "FP", "calc__FP", kind="number"),
                    OpsColumn("fn", "FN", "calc__FN", kind="number"),
                ],
                best_metric_column="calc__f1_score",
                default_sort=[("f1", "desc")],
                filters=[
                    OpsColumn("subset_filter", "subset_id", "subset_id", kind="chip", filterable=True),
                    OpsColumn("class_filter", "Class", "label", filterable=True),
                ],
                default_filters=[OpsFilterRule(column_id="subset_id", operator="equal", value="val")],
            )
        ],
        tags=["tensorflow", "image", "classification", "training"],
    )
])
