from __future__ import annotations

from datapipe.compute import Pipeline
from datapipe_app import DatapipeAPI, RunLogsBackend
from datapipe_app.ops.specs import (
    OpsColumn,
    OpsColumnGroup,
    OpsFilterRule,
    OpsMetricTableSpec,
    OpsRelationSpec,
)
from datapipe_app_ml_ops.ops.ops_specs import (
    DatapipeOpsSpec,
    OpsClassMetricTableSpec,
    OpsDataSpec,
    OpsFrozenDatasetSpec,
    OpsImageAnnotationSpec,
    OpsImageDataSpec,
    OpsImagePredictionViewSpec,
    OpsImageRecordViewSpec,
    OpsModelSpec,
    OpsTrainingSpec,
)
from datapipe.datatable import DataStore
from datapipe.step.batch_generate import BatchGenerate
from datapipe.step.batch_transform import BatchTransform
from datapipe_label_studio.upload_predictions_pipeline import LabelStudioUploadPredictions
from datapipe_label_studio.upload_tasks_pipeline import LabelStudioUploadTasks
from datapipe_ml.metrics.model_selection import FindBestModel
from datapipe.types import Required
from datapipe_ml.training.specs import TrainingResumeConfig, TrainingSyncConfig
from datapipe_ml.tasks.keypoints.freeze import KeypointsFreezeDataset
from datapipe_ml.tasks.keypoints.inference import Inference_KeypointsModel
from datapipe_ml.tasks.keypoints.metrics import CountMetrics_Subset_KeypointsModel
from datapipe_ml.tasks.keypoints.train.yolov8 import Train_YoloV8_KeypointsModel, YoloV8_TrainingConfig

import steps
from config import (
    CLASSES_TO_KEEP,
    DATAPIPE_DIR,
    KEYPOINTS_MODEL_CONFIG,
    datapipe_tmp_folder,
    CLICKHOUSE_RUN_LOGS_URL,
    DBCONN,
    label_studio_storages,
    LABEL_CONFIG,
    LABEL_STUDIO_API_KEY,
    LABEL_STUDIO_URL,
    PROJECT_NAME,
    gpu_executor,
    metrics_executor,
    parallel_io_executor,
)
from data import catalog

pipeline = Pipeline(
    [
        BatchGenerate(
            steps.list_s3_images,
            outputs=["s3_images"],
            labels=[("stage", "annotation")],
        ),
        BatchGenerate(
            steps.list_keypoints_models,
            outputs=["keypoints_model_train"],
            labels=[("stage", "annotation")],
            delete_stale=False
        ),
        BatchTransform(
            func=steps.get_images_without_ground_truth,
            inputs=["s3_images", "image__ground_truth"],
            outputs=["sec__image_without_ground_truth"],
            transform_keys=["image_name"],
            kwargs=dict(primary_keys=["image_name"]),
            labels=[("stage", "annotation")],
        ),
        BatchTransform(
            func=steps.resolve_best_keypoints_model,
            inputs=["keypoints_model_train", "best_keypoints_model"],
            outputs=["best_keypoints_model"],
            transform_keys=["keypoints_model_id"],
            kwargs=dict(
                model_id_column="keypoints_model_id",
                fallback_model_id=KEYPOINTS_MODEL_CONFIG["keypoints_model_id"],
            ),
            labels=[("stage", "annotation")],
        ),
        Inference_KeypointsModel(
            input__image=["s3_images", "sec__image_without_ground_truth"],
            input__keypoints_model=["keypoints_model_train", "best_keypoints_model"],
            output__keypoints_prediction="ls_keypoints_prediction_raw",
            primary_keys=["image_name"],
            bbox_id__name=None,
            image__image_path__name="image_url",
            batch_size_default=1,
            executor_config=gpu_executor(),
            labels=[("stage", "annotation")],
        ),
        BatchTransform(
            func=steps.filter_bboxes_by_classes,
            inputs=["ls_keypoints_prediction_raw"],
            outputs=["ls_keypoints_prediction"],
            transform_keys=["image_name", "keypoints_model_id"],
            labels=[("stage", "annotation")],
            kwargs=dict(
                classes_to_keep=CLASSES_TO_KEEP,
                primary_keys=["image_name"],
                model_id_column="keypoints_model_id",
            ),
        ),
        BatchTransform(
            func=steps.keypoints_to_ls_prediction,
            inputs=["ls_keypoints_prediction", "s3_images"],
            outputs=["images_with_predictions"],
            transform_keys=["image_name", "keypoints_model_id"],
            labels=[("stage", "annotation")],
            kwargs=dict(
                image__image_path__name="image_url",
                primary_keys=["image_name"],
                model_keys=["keypoints_model_id"],
                hide_bboxes=True,
            ),
        ),
        LabelStudioUploadTasks(
            input__item="s3_images",
            output__label_studio_project_task="ls_task",
            output__label_studio_project_annotation="ls_annotations",
            output__label_studio_sync_table="ls_sync",
            ls_url=LABEL_STUDIO_URL,
            api_key=LABEL_STUDIO_API_KEY,
            project_identifier=PROJECT_NAME,
            project_label_config_at_create=LABEL_CONFIG,
            primary_keys=["image_name"],
            columns=["image_url"],
            storages=label_studio_storages(),
            chunk_size=100,
            labels=[("stage", "annotation")],
        ),
        LabelStudioUploadPredictions(
            input__item__has__prediction="images_with_predictions",
            input__label_studio_project_task="ls_task",
            input__best_model="best_keypoints_model",
            output__label_studio_project_prediction="ls_predictions",
            output__label_studio_current_model_version="ls_current_model_version",
            ls_url=LABEL_STUDIO_URL,
            api_key=LABEL_STUDIO_API_KEY,
            project_identifier=PROJECT_NAME,
            primary_keys=["image_name", "keypoints_model_id"],
            model_keys=["keypoints_model_id"],
            labels=[("stage", "annotation")],
        ),
        BatchTransform(
            func=steps.parse_annotations_from_label_studio,
            inputs=["ls_annotations"],
            outputs=["image__ground_truth"],
            labels=[("stage", "annotation")],
            transform_keys=["image_name"],
        ),
        BatchTransform(
            func=steps.split_df_train_val,
            inputs=["image__ground_truth", "image__subset"],
            outputs=["image__subset"],
            labels=[("stage", "train"), ("stage", "train-prepare")],
            transform_keys=["image_name"],
            kwargs=dict(
                primary_keys=["image_name"],
                val_perc=0.25,
                random_seed=42,
            ),
        ),
        KeypointsFreezeDataset(  # type: ignore[list-item]
            input__image="s3_images",
            input__image__ground_truth="image__ground_truth",
            input__subset__has__image="image__subset",
            output__keypoints_frozen_dataset="keypoints_frozen_dataset",
            output__keypoints_frozen_dataset__has__image_gt="keypoints_frozen_dataset__has__image_gt",
            working_dir=str(DATAPIPE_DIR),
            min_within_time="15min",
            min_delta=10,
            primary_keys=["image_name"],
            bbox_id__name=None,
            image__image_path__name="image_url",
            labels=[("stage", "train"), ("stage", "train-prepare")],
        ),
        Train_YoloV8_KeypointsModel(  # type: ignore[list-item]
            input__keypoints_frozen_dataset="keypoints_frozen_dataset",
            input__keypoints_frozen_dataset__has__image_gt="keypoints_frozen_dataset__has__image_gt",
            output__yolov8_train_config="yolov8_train_config",
            output__yolov8_custom_train_config="yolov8_custom_train_config",
            output__keypoints_training_request="keypoints_training_request",
            output__model_keypoints_size_for_resize="model_keypoints_size_for_resize",
            output__keypoints_size_for_resize="keypoints_size_for_resize",
            output__keypoints_frozen_dataset__resized_image_file="keypoints_frozen_dataset__resized_image_file",
            output__keypoints_frozen_dataset__yolo_txt="keypoints_frozen_dataset__yolo_txt",
            output__keypoints_model="keypoints_model_train",
            output__keypoints_model_is_trained_on_keypoints_frozen_dataset=(
                "keypoints_model_is_trained_on_keypoints_frozen_dataset"
            ),
            output__training_status="keypoints_training_status",
            output__keypoints_frozen_dataset__class_names="keypoints_frozen_dataset__class_names",
            max_within_time="1w",
            working_dir=str(DATAPIPE_DIR),
            tmp_folder=datapipe_tmp_folder(),
            yolov8_train_configs=[
                YoloV8_TrainingConfig(
                    model="yolov8n-pose.pt",
                    imgsz=320,
                    batch=8,
                    epochs=30,
                    exist_ok=True,
                )
            ],
            sync_config=TrainingSyncConfig(
                enabled=True,
                interval_s=30,
                retries=3,
                retry_sleep_s=30,
            ),
            resume_config=TrainingResumeConfig(
                continue_train_failed_models=True,
                min_completed_epochs=1,
                checkpoint="last",
                max_attempts=10,
                reset_attempts_after="10m",
                lease_ttl_s=60,
                heartbeat_interval_s=10,
            ),
            primary_keys=["image_name"],
            bbox_id__name=None,
            labels=[("stage", "train")],
            allow_sample_size_mismatch=True,
            model_suffix="_e2e",
            prepare_data_executor_config=parallel_io_executor(),
        ),
        Inference_KeypointsModel(
            input__image=["s3_images", "image__subset"],
            input__keypoints_model="keypoints_model_train",
            output__keypoints_prediction="keypoints_prediction_train_raw",
            primary_keys=["image_name"],
            bbox_id__name=None,
            labels=[("stage", "train"), ("stage", "inference")],
            image__image_path__name="image_url",
            batch_size_default=1,
            executor_config=gpu_executor(),
            filters={"subset_id": "val"},
        ),
        BatchTransform(
            func=steps.filter_bboxes_by_classes,
            inputs=["keypoints_prediction_train_raw"],
            outputs=["keypoints_prediction_train"],
            transform_keys=["image_name", "keypoints_model_id"],
            labels=[("stage", "train"), ("stage", "inference")],
            kwargs=dict(
                classes_to_keep=CLASSES_TO_KEEP,
                primary_keys=["image_name"],
                model_id_column="keypoints_model_id",
            ),
        ),
        CountMetrics_Subset_KeypointsModel(
            input__image__ground_truth="image__ground_truth",
            input__subset__has__image="image__subset",
            input__keypoints_prediction="keypoints_prediction_train",
            output__keypoints_model__metrics_on__image="keypoints_model_train__metrics_on_image",
            output__keypoints_model__metrics_by_cls_on__subset="keypoints_model_train__metrics_by_cls_on_subset",
            output__keypoints_model__metrics_on__subset="keypoints_model_train__metrics_on_subset",
            primary_keys=["image_name"],
            bbox_id__name=None,
            keypoints_model_primary_keys=["keypoints_model_id"],
            labels=[("stage", "train"), ("stage", "count-metrics")],
            minimum_iou=0.5,
            executor_config=metrics_executor(),
            # filters={"subset_id": "val"},
        ),
        FindBestModel(
            input__model="keypoints_model_train",
            input__model__metrics_on__subset="keypoints_model_train__metrics_on_subset",
            output__attr__model__is_best="attr__keypoints_model__is_best",
            output__best_model="best_keypoints_model",
            subset_id="val",
            is_best__name="keypoints_model__is_best",
            primary_keys=["keypoints_model_id"],
            metric__name="calc__pose_mAP50_95",
            func="max",
            group_by=None,
            labels=[("stage", "train"), ("stage", "count-metrics")],
        ),
        BatchTransform(
            func=steps.download_images,
            inputs=["s3_images"],
            outputs=["local_images"],
            transform_keys=["image_name"],
            labels=[("stage", "fiftyone")],
            executor_config=parallel_io_executor(),
            kwargs=dict(
                image__image_path__name="image_url",
                image__local_image_path__name="local_path",
            ),
        ),
        BatchTransform(
            func=steps.publish_to_fiftyone,
            inputs=["local_images"],
            outputs=["fiftyone_images"],
            labels=[("stage", "fiftyone")],
            kwargs=dict(
                primary_keys=["image_name"],
                image__image_path__name="local_path",
            ),
        ),
        BatchTransform(
            func=steps.publish_to_fiftyone_ground_truth,
            inputs=["local_images", Required("image__ground_truth"), Required("image__subset")],
            outputs=["fiftyone_annotations"],
            labels=[("stage", "fiftyone")],
            kwargs=dict(
                primary_keys=["image_name"],
                image__image_path__name="local_path",
            ),
        ),
        BatchTransform(
            func=steps.publish_to_fiftyone_predictions_from_best_model,
            inputs=["local_images", "keypoints_prediction_train", Required("best_keypoints_model")],
            outputs=["fiftyone_predictions_from_best_model"],
            transform_keys=["image_name", "keypoints_model_id"],
            labels=[("stage", "fiftyone")],
            kwargs=dict(
                primary_keys=["image_name"],
                model_keys=["keypoints_model_id"],
                image__image_path__name="local_path",
            ),
        ),
    ]
)

ds = DataStore(DBCONN)
app = DatapipeAPI(
    ds,
    catalog,
    pipeline,
    run_logs_backend=RunLogsBackend.clickhouse(CLICKHOUSE_RUN_LOGS_URL),
)

app.add_specs([
    DatapipeOpsSpec(
        id="person_pose",
        title="Person Pose Detection",
        description="YOLO pose training pipeline over frozen image snapshots.",
        icon="activity",
        color="teal",
        data=OpsDataSpec(
            tables=[
                "s3_images",
                "image__ground_truth",
                "image__subset",
                "keypoints_frozen_dataset",
                "keypoints_model_train",
                "keypoints_model_train__metrics_on_subset",
                "keypoints_model_train__metrics_by_cls_on_subset",
            ],
            item_table="s3_images",
            label_table="image__ground_truth",
            subset_table="image__subset",
            image_view=OpsImageDataSpec(
                kind="image",
                image_table="s3_images",
                image_primary_key_columns=("image_name",),
                image_url_column="image_url",
                subset_table="image__subset",
                subset_join_columns={"image_name": "image_name"},
                subset_column="subset_id",
                records_show_subset=True,
                ground_truth=OpsImageAnnotationSpec(
                    table="image__ground_truth",
                    primary_key_columns=("image_name",),
                    bboxes_column="bboxes",
                    labels_column="labels",
                    join_columns={"image_name": "image_name"},
                    role="gt",
                ),
                records_show_ground_truth=True,
                preview_size=84,
                modal_max_side=1100,
                detail_max_side=1600,
            ),
        ),
        frozen_dataset=OpsFrozenDatasetSpec(
            table="keypoints_frozen_dataset",
            id_column="keypoints_frozen_dataset_id",
            created_at_column="keypoints_frozen_dataset__created_at",
            label_mode="timestamp",
            split_columns={
                "train": "keypoints_frozen_dataset__train_images_count",
                "val": "keypoints_frozen_dataset__val_images_count",
                "test": "keypoints_frozen_dataset__test_images_count",
            },
            models_count_relation_id="model_trained_on_frozen_dataset",
            record_view=OpsImageRecordViewSpec(
                kind="image",
                table="keypoints_frozen_dataset__has__image_gt",
                scope_column="keypoints_frozen_dataset_id",
                primary_key_columns=("image_name", "subset_id"),
                image_url_column="image__image_path",
                bboxes_column="bboxes",
                labels_column="labels",
                preview_size=84,
                modal_max_side=1100,
                detail_max_side=1600,
            ),
            columns=[
                OpsColumn(
                    "keypoints_frozen_dataset_id",
                    "Dataset",
                    "keypoints_frozen_dataset_id",
                    kind="link",
                    link_to="frozen_dataset",
                    filterable=True,
                ),
                OpsColumn(
                    "created_at",
                    "Frozen at",
                    "keypoints_frozen_dataset__created_at",
                    kind="datetime",
                    filterable=True,
                ),
                OpsColumn("split", "Split", "split", kind="split"),
                OpsColumn("models", "Models", "models_count", kind="models_count"),
            ],
            default_sort=[("created_at", "desc")],
        ),
        model=OpsModelSpec(
            table="keypoints_model_train",
            id_column="keypoints_model_id",
            artifact_uri_column="keypoints_model__model_path",
            is_best_table="attr__keypoints_model__is_best",
            is_best_column="keypoints_model__is_best",
            prediction_view=OpsImagePredictionViewSpec(
                kind="image",
                table="keypoints_prediction_train",
                model_id_column="keypoints_model_id",
                image_primary_key_columns=("image_name",),
                image_url_table="s3_images",
                image_url_column="image_url",
                image_url_join_columns={"image_name": "image_name"},
                prediction=OpsImageAnnotationSpec(
                    table="keypoints_prediction_train",
                    primary_key_columns=("image_name", "keypoints_model_id"),
                    bboxes_column="bboxes",
                    labels_column="labels",
                    scores_column="prediction__detection_scores",
                    role="prediction",
                ),
                ground_truth=OpsImageAnnotationSpec(
                    table="image__ground_truth",
                    primary_key_columns=("image_name",),
                    bboxes_column="bboxes",
                    labels_column="labels",
                    join_columns={"image_name": "image_name"},
                    role="gt",
                ),
                subset_table="image__subset",
                subset_join_columns={"image_name": "image_name"},
                subset_column="subset_id",
                preview_size=84,
                modal_max_side=1100,
                detail_max_side=1600,
            ),
        ),
        training=OpsTrainingSpec(
            status_table="keypoints_training_status",
            artifact_columns={
                "manifest": "training_status__manifest_path",
                "run_dir": "training_status__run_dir",
            },
            columns=[
                OpsColumn(
                    "run_id",
                    "Run ID",
                    "training_status__run_key",
                    kind="link",
                    link_to="training_run",
                    filterable=True,
                ),
                OpsColumn(
                    "keypoints_model_id",
                    "Model",
                    "keypoints_model_id",
                    kind="link",
                    link_to="model",
                    filterable=True,
                ),
                OpsColumn(
                    "keypoints_frozen_dataset_id",
                    "Frozen dataset",
                    "keypoints_frozen_dataset_id",
                    kind="link",
                    link_to="frozen_dataset",
                    filterable=True,
                ),
                OpsColumn(
                    "started_at",
                    "Started",
                    "training_status__started_at",
                    kind="datetime",
                    filterable=True,
                ),
                OpsColumn("duration", "Duration", "duration_seconds", kind="duration"),
                OpsColumn(
                    "status",
                    "Status",
                    "training_status__status",
                    kind="status",
                    filterable=True,
                ),
            ],
            default_sort=[("started_at", "desc")],
        ),
        relations=[
            OpsRelationSpec(
                id="model_trained_on_frozen_dataset",
                table="keypoints_model_is_trained_on_keypoints_frozen_dataset",
                from_entity="model",
                from_column="keypoints_model_id",
                to_entity="frozen_dataset",
                to_column="keypoints_frozen_dataset_id",
            )
        ],
        metrics=[
            OpsMetricTableSpec(
                id="model_metrics",
                title="Model metrics",
                table="keypoints_model_train__metrics_on_subset",
                metric_source="keypoints_model_train__metrics_on_subset",
                primary_key_columns=["keypoints_model_id", "subset_id"],
                entity_links={
                    "model": "keypoints_model_id",
                    "subset": "subset_id",
                },
                primary_columns=[
                    OpsColumn(
                        "keypoints_model_id",
                        "Model",
                        "keypoints_model_id",
                        filterable=True,
                        link_to="model",
                    ),
                    OpsColumn("subset_id", "Subset", "subset_id", kind="chip", filterable=True),
                ],
                metric_columns=[
                    OpsColumnGroup(
                        "Pose",
                        [
                            OpsColumn("pose_mAP50_95", "Pose mAP50-95", "calc__pose_mAP50_95", kind="number"),
                            OpsColumn("pose_mAP50", "Pose mAP50", "calc__pose_mAP50", kind="number"),
                            OpsColumn("pose_P", "Pose P", "calc__pose_P", kind="number"),
                            OpsColumn("pose_R", "Pose R", "calc__pose_R", kind="number"),
                            OpsColumn("pose_support", "Pose support", "calc__pose_support", kind="number"),
                        ],
                    ),
                    OpsColumnGroup(
                        "Precision",
                        [
                            OpsColumn("weighted_precision", "W-Precision", "calc__weighted_precision", kind="number"),
                            OpsColumn("macro_precision", "M-Precision", "calc__macro_precision", kind="number"),
                        ],
                    ),
                    OpsColumnGroup(
                        "Recall",
                        [
                            OpsColumn("weighted_recall", "W-Recall", "calc__weighted_recall", kind="number"),
                            OpsColumn("macro_recall", "M-Recall", "calc__macro_recall", kind="number"),
                        ],
                    ),
                    OpsColumnGroup(
                        "F1",
                        [
                            OpsColumn("weighted_f1", "W-F1", "calc__weighted_f1_score", kind="number"),
                            OpsColumn("macro_f1", "M-F1", "calc__macro_f1_score", kind="number"),
                        ],
                    ),
                    OpsColumn("accuracy", "Accuracy", "calc__accuracy", kind="number"),
                    OpsColumn("support", "Support", "calc__support", kind="number"),
                ],
                best_metric_column="calc__pose_mAP50_95",
                default_sort=[("pose_mAP50_95", "desc")],
                filters=[OpsColumn("subset_filter", "Subset", "subset_id", kind="chip", filterable=True)],
                default_filters=[OpsFilterRule(column_id="subset_id", operator="equal", value="val")],
            ),
        ],
        class_metrics=[
            OpsClassMetricTableSpec(
                id="subset_class_metrics",
                title="Subset class metrics",
                table="keypoints_model_train__metrics_by_cls_on_subset",
                metric_source="keypoints_model_train__metrics_by_cls_on_subset",
                primary_key_columns=["keypoints_model_id", "subset_id", "label"],
                entity_links={
                    "model": "keypoints_model_id",
                    "subset": "subset_id",
                    "class": "label",
                },
                primary_columns=[
                    OpsColumn(
                        "keypoints_model_id",
                        "Model",
                        "keypoints_model_id",
                        filterable=True,
                        link_to="model",
                    ),
                    OpsColumn("subset_id", "Subset", "subset_id", kind="chip", filterable=True),
                    OpsColumn("label", "Class", "label", filterable=True, link_to="class"),
                ],
                metric_columns=[
                    OpsColumn("precision", "Precision", "calc__precision", kind="number"),
                    OpsColumn("recall", "Recall", "calc__recall", kind="number"),
                    OpsColumn("f1", "F1", "calc__f1_score", kind="number"),
                    OpsColumn("support", "Support", "calc__support", kind="number"),
                ],
                filters=[OpsColumn("subset_filter", "Subset", "subset_id", kind="chip", filterable=True)],
                default_filters=[OpsFilterRule(column_id="subset_id", operator="equal", value="val")],
            )
        ],
        tags=["yolo", "image", "keypoints", "training"],
    )
])
