"""active

Revision ID: 5ae5b084f01c
Revises: e7716e02d74b
Create Date: 2023-07-12 01:43:01.342503

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "5ae5b084f01c"
down_revision = "e7716e02d74b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "datapipe_step_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("step", sa.String(length=100), nullable=True),
        sa.Column(
            "event_ts",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("event", sa.String(length=100), nullable=True),
        sa.Column("event_payload", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("user_profile", sa.Column("active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profile", "active")
    op.drop_table("datapipe_step_events")
    # ### end Alembic commands ###
