"""active

Revision ID: 5ae5b084f01c
Revises: e7716e02d74b
Create Date: 2023-07-12 01:43:01.342503

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5ae5b084f01c"
down_revision = "e7716e02d74b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "datapipe_step_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("step", sa.String(length=100), nullable=True),
        sa.Column("event_ts", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("event", sa.String(length=100), nullable=True),
        sa.Column("event_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("user_profile", sa.Column("active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profile", "active")
    op.create_table(
        "user_profiles_meta",
        sa.Column("user_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("hash", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "create_ts",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "update_ts",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "process_ts",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "delete_ts",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("user_id", name="user_profiles_meta_pkey"),
    )
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("lang", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "offer_clicks",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("user_id", name="user_profiles_pkey"),
    )
    op.drop_table("datapipe_step_events")
    # ### end Alembic commands ###
